In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

In [3]:
(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


In [4]:
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

In [5]:
x_train = np.expand_dims(x_train, axis=-1)
x_test = np.expand_dims(x_test, axis=-1)

In [6]:
model = keras.Sequential([
keras.layers.Conv2D(32, (3,3), padding='same', activation='relu',input_shape=(28,28,1)),
keras.layers.MaxPooling2D((2,2)),
keras.layers.Conv2D(64, (3,3), padding='same', activation='relu'),
keras.layers.MaxPooling2D((2,2)),
keras.layers.Flatten(),
keras.layers.Dense(128, activation='relu'),
keras.layers.Dense(10, activation='softmax')
])

In [7]:
model.compile(optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [8]:
history = model.fit(x_train, y_train, epochs=1, validation_data=(x_test,y_test))

1875/1875 [==============================] - 62s 32ms/step - loss: 0.4052 - accuracy: 0.8540 - val_loss: 0.3353 - val_accuracy: 0.8756


In [9]:
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

313/313 [==============================] - 3s 9ms/step - loss: 0.3353 - accuracy: 0.8756
Test accuracy: 0.8755999803543091


In [10]:
predictions = model.predict(x_test)

313/313 [==============================] - 3s 9ms/step


In [11]:
def chooseClass(prediction):
  predictionClass = 0
  maxProbability = 0
  for i in range(len(prediction)):
    probability = prediction[i]
    if probability > maxProbability:
      maxProbability = probability
      predictionClass = i
  return predictionClass

In [12]:
y_pred = np.array(list(map(chooseClass, predictions)))

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_pred=y_pred, y_true=y_test))
print(classification_report(y_pred=y_pred, y_true=y_test))

[[831   0   5  25   2   0 126   0  11   0]
 [  1 969   0  22   2   0   4   0   2   0]
 [ 16   1 677  11  95   0 198   0   2   0]
 [ 17   2   1 920  11   0  48   0   1   0]
 [  0   1  27  53 704   0 215   0   0   0]
 [  0   0   0   0   0 964   0  12   0  24]
 [119   1  24  34  25   0 782   0  15   0]
 [  0   0   0   0   0   6   0 958   1  35]
 [  0   1   0   5   0   1   6   4 983   0]
 [  0   0   0   0   0   2   1  29   0 968]]
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      1000
           1       0.99      0.97      0.98      1000
           2       0.92      0.68      0.78      1000
           3       0.86      0.92      0.89      1000
           4       0.84      0.70      0.77      1000
           5       0.99      0.96      0.98      1000
           6       0.57      0.78      0.66      1000
           7       0.96      0.96      0.96      1000
           8       0.97      0.98      0.98      1000
           9       0.94     